### ISSUE TITLE
Cursor not visibile when setting the cursor shape to block

### ISSUE THREAD

**Issue by fabiopelosin** [henrikdahl/hyperterm-chesterish#4]
## Issue

The cursor is not visible when it is set to block via the `CursorShape` escape sequence. The issue is not present if this plug-in is disabled.

## How to reproduce

```echo
printf '\033]50;CursorShape=0\007’
```

## Related info

The functionality is described in this issue: https://github.com/zeit/hyper/issues/270

**Comment by henrikruscon** [comment]
I'll fix this asap ✌️

**Comment by fabiopelosin** [comment]
Ace thanks... and thank you for the awesome project

**Comment by gravitinos** [comment]
Yeah, I'm not able to change the cursor to block.

**Comment by henrikruscon** [comment]
Sorry for the delay! Was on vacation in the Caribbean 🌴 

I just pushed a version that fixes this issue ✌️

It also separates the custom tabs into its own plugin so that it's not limited to my themes.

https://github.com/henrikdahl/hyper-tabs-enhanced

**NOTE:** Make sure you replace `hyperterm-chesterish` with `hyper-chesterish` since there's been a name change.
